### PR TITLE
correct train ticket payments

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by michielbdejong** [comment]
@hugoroy and @piks3l please check if the following data is *exactly* correct:

* During Q4 2017, Hugo transferred money to Chris once, namely:
  * 740 euros on 18 December
* During Q1 2018 so far, Hugo transferred money to Chris twice, namely:
  * 998 euros on 9 January (but this includes the 740 already paid in December?)
  * 139.20 euros on 7 February (not 138 euros)
* On 15 December, Chris paid 198 euros for a train ticket to Paris
* On 16 January, Chris paid 138 euros (not 139.20) for a train ticket to Utrecht

**Comment by michielbdejong** [comment]
ok, then i think what happened was that the 740 eur was part of the 998 eur. will update!

**Comment by piks3l** [comment]
Yes, I the 740 were part of the 998, sorry if it was misleading. It contains also the 198 for the train ticket to Paris if I'm not mistaken.

**Comment by piks3l** [comment]
> * 139.20 euros on 7 February (not 138 euros)
> Correct.

Wasn't it a fee for bank transfer or something ?

**Comment by michielbdejong** [comment]
> Wasn't it a fee for bank transfer or something?

OK, that makes sense, in that case, you should add the 1.20 eur fee under 'operations'.

> Yes, I the 740 were part of the 998, sorry if it was misleading. It contains also the 198 for the train ticket to Paris if I'm not mistaken.

We don't need to specify if a transfer between you and Hugo is "for" something or "contains" some costs. You can simply write down three things:
* exact amount and date whenever money moves between 'kept safe by Chris' and 'kept safe by X' (in this case, X was Hugo).
* exact amount and date of when you pay something for the project. That can be server hosting, train tickets, bank transaction fees.
* hours you worked times 20 euros per hour.

Then at the end of each quarter we take your old "money kept safe by Chris" amount, substract any productions costs paid and hours worked (meaning there is now **less* money kept safe by you), and then add money that was transferred to you (meaning that after such a transfer, there is **more** money kept safe by you).

The amounts don't need to match exactly, it could be that you start with 100 eur kept safe by you, then through paying for production costs and throw writing hours you go for instance -123 euros, to -23 euros. Then it could be that Hugo transfers exactly 23 euros to you and you end up exactly at zero, but it could also be some unrelated amount. For instance, if he transfers 200 euros to you, you would go from -23 to +177, and that would be fine, you don't have to say these 200 euros were "for" this or that, or that they "contain" the 123 euros which you wrote down earlier. We just take you starting balance, subtract something, add something, and a finish balance comes out, which will be your new starting balance for the next quarter.

Does that make sense?

**Comment by michielbdejong** [comment]
That's why I removed your comments in this line: https://github.com/tosdr/1901/pull/4/files#diff-00b631681a34d2ae682b90a9c251c8feL17 - all we need to write down is that a transfer happened, and the two balances (yours and Hugo's) are adjusted, doesn't matter what *for* that transfer happened.

**Comment by piks3l** [comment]
> The amounts don't need to match exactly, it could be that you start with 100 eur kept safe by you, then through paying for production costs and throw writing hours you go for instance -123 euros, to -23 euros. Then it could be that Hugo transfers exactly 23 euros to you and you end up exactly at zero, but it could also be some unrelated amount. For instance, if he transfers 200 euros to you, you would go from -23 to +177, and that would be fine, you don't have to say these 200 euros were "for" this or that, or that they "contain" the 123 euros which you wrote down earlier. We just take you starting balance, subtract something, add something, and a finish balance comes out, which will be your new starting balance for the next quarter.
> 
> Does that make sense?

Err... No, sorry, not really. Let me see if I got it right:
* I start at 0 kept safe
* I work 1h, the balance goes to -20
* Hugo pays it, it goes back to 0

Is that right ?

**Comment by michielbdejong** [comment]
That would be correct yes, you can always just ask Hugo to pay exactly the amount that makes your balance go to zero.

**Pull request merged**
